### ISSUE TITLE
config.yaml has a readlength parameters which is not mentioned in the README

### ISSUE THREAD

**Issue by aleighbrown** [zavolanlab/PAQR_KAPAC#13]
In the config.yaml there's a parameter for readlength which I did not see mention of in the readme and only just noticed; line 99. 
```
# read length of the study (when different samples have different read length
# it is suggested to take the maximum)
# the read length is used to define regions upstream of valid 3' ends with
# expected decrease in read coverage
relUse.read_length: 100
```

Should this be appropiately set? I'd been trying to run on 75 bp reads and I'm not sure if that flag is going to be causing issues. Anyway, if it's something people should be adjusting per their study it might be helpful to move it up in the config.yaml next to the other parameters which need to be custom set. Or to mention in the read.me, but to be clear I realize this is my fault for not properly reading the config file before :)

**Comment by koljaLanger** [comment]
Thanks for the comment.

We tried to set the config file such that it follows the steps in the snakemake pipeline. Anyway, we should mention it in the README. Many thanks for pointing it out to us.

For clarification: the read_length parameter is not of paramount importance as long as the read length is relatively close to 100 (which is set as default value). In your case, 75 would make not much of a difference compared to 100. However, if the read length gets to e.g. 500, we would expect a different coverage pattern, e.g. downstream of breaking points like proximal poly(A) sites. In this case it is important to change the parameter.
