### ISSUE TITLE
annotation files for mm10

### ISSUE THREAD

**Issue by xflicsu** [zavolanlab/PAQR_KAPAC#3]
Hello, PAQR_KAPAC is a powerful tool to investigate APA.
You have provided  two annotation file of human.
data/annotation/clusters.hg38.canonical_chr.tandem.noOverlap_strand_specific.bed
data/annotation/full_transcripts.hg38.canonical_chr.tandem.noOverlap_strand_specific.bed

Now, I try to  investigate APA of mouse.
So, could provide the annotation files of mm10?

**Comment by fgypas** [comment]
Hi @xflicsu . Thank you for your interest in PAQR and KAPAC. We will come back to you in a few days with the requested files.

**Comment by koljaLanger** [comment]
Hi @xflicsu 
We updated the repository and it contains an 'mm10' directory now under PAQR/data/annotation with both files you were asking for. 
I close the issue for now, hoping that this is what you actually require. If this is not the case, please feel free to open the issue again.
