### ISSUE TITLE
snakemake symlink problem

### ISSUE THREAD

**Issue by aleighbrown** [zavolanlab/PAQR_KAPAC#8]
```
snakemake -s part_two.Snakefile -n -p
MissingInputException in line 42 of /SAN/vyplab/alb_projects/tools/PAQR_KAPAC/PAQR/part_two.Snakefile:
Missing input files for rule create_coverages:
test_study/valid_samples/wt_1.bam
```
 
Link 235 in the part_one.Snakefile creates a broken a symlink if config['dir.input"] is already a full path
```
bam_file = "../../" + config["dir.input"] + "/" + config[curr_uuid]['bam'] + ".bam"
```

The fix here was just removing the unnecessary "../../"

**Comment by koljaLanger** [comment]
Many thanks for the comment. You are right in the sense that we intended the program to run with relative path which is the cleaner way in our ways.

I included an additional sentence in the PAQR readme to stress this point.
Best
Ralf
